version: '3'

services:
  php-fpm:
    build:
      context: ./php
    volumes:
      - ./src/www:/var/www
  nginx:
    build:
      context: ./nginx
    volumes:
      - ./src/www:/var/www
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - php-fpm
    ports:
      - "80:80"      
